<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(1);
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	
	$key = new Application_Model_DbTable_DbKeycode();
	$dataInfo=$key->getKeyCodeMiniInv(TRUE);
		
	
	$title = $tr->translate("CHANGE_PASSWORD");
	$this->headTitle($title); 
	echo $this->headTitle();
	
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$currentLang = $dbGb->currentlang();
	$systemLink = $dbGb->systemLink();
	
	
	
	$dbGb = new Application_Model_DbTable_DbGlobal();
	
	$defaultLogo = $this->baseUrl()."/images/logo.png";
	if(!empty($dataInfo['logo'])){
		$logo = $systemLink.'/images/Logo/'.$dataInfo['logo'];
		if ($dbGb->does_url_exists($logo)){
			$defaultLogo = $systemLink.'/images/Logo/'.$dataInfo['logo'];
		}
	}
	
?>
	<div class="login-bg access-login"></div>
	<div class="container login-area">
		<div class="section">
			<div class="row ">
                <div class="col s12 pad-0">
					<div class="spacer-xlarge"></div>
					<div class="center">
						<div class="center iconpassword"></div>
					</div>
					<h5 class="bot-20 sec-tit center white-text"><?php echo $title;?></h5>
					<form id="frmChangePassword" method="post" action="">
						<div class="row">
							<div class="input-field col s10 offset-s1">
							  <input id="pass2" type="password" class="validate" name="currentPassword"  >
							  <label for="pass2"><?php echo $tr->translate("CURRENT_PASSWORD");?></label>
							</div>
						</div>

						<div class="row">
							<div class="input-field col s10 offset-s1">
								<input id="pass3" type="password" class="validate" name="newPassword" >
								<label for="pass3"><?php echo $tr->translate("NEW_PASSWORD");?></label>
							</div>
						</div>
						<div class="row">
							<div class="input-field col s10 offset-s1">
								<input id="pass4" type="password" class="validate" name="comifrmPassword" >
								<label for="pass4"><?php echo $tr->translate("CONFIRM_PASSWORD");?></label>
							</div>
						</div>
						
						<div class="row center">
							<div class="input-field col s10 offset-s1">
							<button type="submit" class="full-width waves-effect waves-light btn-large bg-primary "><?php echo $tr->translate("CHANGE_PASSWORD");?> <i class="mdi mdi-lock-reset"></i></button>
							</div>
							<div class="spacer"></div>
							<div class="spacer"></div>
							<div class="links">
								<a href="<?php echo $this->baseUrl()."/home"?>" class='waves-effect preloader-trigger'>
									<i class="mdi mdi-backup-restore"></i> <?php echo $tr->translate("BACK_HOME");?>
								</a>        
							</div>
							<div class="spacer"></div>
						</div>
					</form>

				</div>
			</div>
		</div>
	</div>
	<script>
		
		$(document).on('click', 'form button[type=submit]', function(e) {
			var currentPassword = $('#pass2').val();
			var newPassword = $('#pass3').val();
			var comifrmPassword = $('#pass4').val();
			if(currentPassword==''){
				displayActionToast(1);
				return false;
			}
			if(newPassword==''){
				displayActionToast(2);
				return false;
			}
			if(comifrmPassword==''){
				displayActionToast(3);
				return false;
			}
			if(newPassword != comifrmPassword ){
				displayActionToast(4);
				return false;
			}
			if(newPassword == currentPassword ){
				displayActionToast(10);
				return false;
			}
			cheking = false;
			urlValidate = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'validatechangepass'));?>';
			$.ajax({
				url: urlValidate,
				type: "post",
				data:{
					'currentPassword':currentPassword
					,'newPassword':newPassword
					,'comifrmPassword':comifrmPassword
				},
				success: function(data){
					if(data==0){
						displayActionToast(5);
						 cheking = false;
					}else{
						$('.preloader-background').css("display","flex");
						 $('#frmChangePassword').submit();
					}
				
				},
				error:function(err){
					
				}
			});
			
			return false;
		});
		function displayActionToast(key){
			M.Toast.dismissAll();
			var message;
			if(key==1){
				message="<?php echo $tr->translate("MSG_ENTER_CURRENT_PASSWORD");?>";
			}else if(key==2){
				message="<?php echo $tr->translate("MSG_ENTER_NEW_PASSWORD");?>";
			}else if(key==3){
				message="<?php echo $tr->translate("MSG_ENTER_COMFIRM_PASSWORD");?>";
			}else if(key==4){
				message="<?php echo $tr->translate("MSG_COMFIRM_AND_NEW_PASSWORD");?>";
			}else if(key==5){
				message="<?php echo $tr->translate("WRONG_CURRENT_PASSWORD");?>";
			}else if(key==10){
				message="<?php echo $tr->translate("MSG_OLD_AND_NEW_PASSWORD");?>";
			}
             var toastHTML = '<span>'+message+'</span><button class="btn-flat toast-action" onclick="M.Toast.dismissAll(),resetForm();"><?php echo $tr->translate("CLEAR");?></button>';
				M.toast({html: toastHTML});
         }
        function resetForm(){
        	document.getElementById("frmChangePassword").reset();
           }
	</script>
















