 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("PAYMENT"));
	echo $this->headTitle();
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$systemLink = $dbGb->systemLink();
	$currentlang = $dbGb->currentlang();
	
	$frm = $this->formFilter;
	$querystring = $this->queryString;
	
?>
<div class="bgBodyhome"></div>	
<div class="bgpayment-list-info "></div>
<!-- Modal Structure -->
<div id="modalFilter" class="modal bottom-sheet white dark-text">
	<div class="modal-content">
		<div class="container">
			<div class="section ui-select">
				<form method="GET">
					<div class="row ">
						<div class="col s12 pad-0"><h5 class="bot-20 sec-tit  "><?php echo $tr->translate("FILTER"); ?></h5>        
							<div class="row">
								<div class="input-field col s6">
									<?php echo $frm->getElement('startDate');?>
								  <label><?php echo $tr->translate("FROM_DATE"); ?></label>
								</div>
								<div class="input-field col s6">
									<?php echo $frm->getElement('endDate');?>
								  <label><?php echo $tr->translate("TO_DATE"); ?></label>
								</div>
								<div class="input-field colLeft col s6">
									<?php echo $frm->getElement('academicYear');?>
								  <label><?php echo $tr->translate("ACADEMIC_YEAR"); ?></label>
								</div>
								<div class="input-field colRight col s6">
									<?php echo $frm->getElement('paymentMethod');?>
								  <label><?php echo $tr->translate("PAYMENT_METHOD"); ?></label>
								</div>
								<div class="input-field col s12">
									<button type="submit" class="fullsize waves-effect waves-light btn btn-rounded primary lighten-2" name="search"><?php echo $tr->translate("SEARCH"); ?></button>
								</div>
							</div>
							
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<div class="bgBody-listview gradientYellow">
	<div class="container">
		<div class="section">
			<div class="row">
				<div class="col s12 pad-0 blog-page-title">
					<div class="page-icon">
						<i class="mdi mdi-cash-multiple "></i>
					</div>
					<h5 class="sec-page-tit  ">
						<?php echo $tr->translate("PAYMENT"); ?>
					</h5>
					<span class="sec-page-desc">
						<?php echo $tr->translate("PAYMENT_PAGE_DESC"); ?>
					</span>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="spacer-small"></div>
<div class="spacer-medium"></div>
<div id="listRecord" class="payment-list-info ">
	<?php $stickyBlog=""; if(!empty($this->row)){ foreach($this->row AS $payment){ 
	
			$yearPMT = date("Y",strtotime($payment['paymentDate'])); 
			$dayPMT = date("d",strtotime($payment['paymentDate'])); 
			$monthPMT = date("M",strtotime($payment['paymentDate'])); 
			$monthKey = date("m",strtotime($payment['paymentDate'])); 
			

			if($currentlang==1){
				$yearPMT = $dbGb->getNumberInkhmer($yearPMT);
				$dayPMT = $dbGb->getNumberInkhmer($dayPMT);
				$monthPMT = $dbGb->getMonthInkhmer($monthKey);
				
			}
	
	?>
	<?php if($stickyBlog!=date("mY",strtotime($payment['paymentDate']))){?>
	<div class="stickyBlog">
		<div class="stickyTitle">
			<?php echo date("M-Y",strtotime($payment['paymentDate'])); ?>
		</div>
	</div>
	<?php } $stickyBlog =date("mY",strtotime($payment['paymentDate'])); ?>
	<div class="container">
		<div class="ui-grids payment_list-row">
			<div class="row mrg-0">
				<div class="col s7 blg-payment-left">
					<h3 class="title-payment"><?php echo $payment['receiptNo']; ?> </h3>
					<span class="payment-info"><i class="mdi mdi-calendar-clock "></i> <strong class="mark-title"><?php echo $dayPMT."-".$monthPMT."-".$yearPMT; ?></strong></span>
					<span class="payment-info"><?php echo $tr->translate("CLASS_NAME"); ?> <strong class="mark-title"><?php echo $payment['groupCode']; ?></strong></span>
					<span class="payment-info"><?php echo $tr->translate("ACADEMIC_YEAR"); ?> <strong class="mark-title"><?php echo $payment['academicYear']; ?></strong></span>
					<span class="payment-info"><?php echo $tr->translate("CASHIER"); ?> <strong class="mark-title"><?php echo $payment['userName']; ?></strong></span>
				</div>
				<div class="col s5 blg-payment-right">
					<h2 class="amount">$ <?php echo number_format($payment['paid_amount'],2); ?></h2>
					<span class="payment-info"><?php echo $tr->translate("PMT_METHOD"); ?> <strong class="mark-title"><?php echo $payment['paymentMethod']; ?></strong></span>
					<?php if($payment['payment_method']!=1){?>
					<span class="payment-info"> <strong class="mark-title"><?php echo $payment['methodSerialNumber']; ?></strong></span>
					<?php } ?>
					<?php if($payment['is_void']==1){?>
					<span class="payment-info"> <strong class="mark-title"><?php echo $payment['voidTitle']; ?></strong></span>
					<?php } ?>
					<div class="spacer-small"></div>
					<div class="spacer-small"></div>
					<a class="waves-effect waves-light btn btn-rounded  lighten-2" onClick="getPopupContent(<?php echo $payment['id']; ?>)" >
						<?php echo $tr->translate("MORE_DETAIL"); ?>
					</a>
				</div>
			</div>
		</div>
	</div>
	<?php } ?>
	<?php }else{ ?>
	<div class="ui-grids empty-data">
		<div class="row mrg-0">
			<div class="col s12 ">
				<h3 class="title-empty"><?php echo $tr->translate("EMPTY_RECORD"); ?></h3>
			</div>
		</div>
		
	</div>
	<?php } ?>	
</div>

<?php if(!empty($this->row)){?>
<div class="ui-grids ">
	<div class="row mrg-0">
		<div class="col s12 center " >
			<p id="totalRecord" class="total-record"><?php echo count($this->row)."/".$this->allRow; ?></p>
			<h3 class="title-empty recordMessage"><?php echo $tr->translate("SCROLL_FOR_MORE_DATA"); ?></h3>
		</div>
	</div>
	<div class="row mrg-0">
		<div class="col s12 center valign-wrapper" style="height: 100px;">
			<div id="preLoadRecord" class="preloader-wrapper small ">
				<div class="spinner-layer spinner-blue">
					<div class="circle-clipper left">
						<div class="circle"></div>
					</div>
					<div class="gap-patch">
						<div class="circle"></div>
					</div>
					<div class="circle-clipper right">
						<div class="circle"></div>
					</div>
				</div>

				<div class="spinner-layer spinner-red">
					<div class="circle-clipper left">
						<div class="circle"></div>
					</div>
					<div class="gap-patch">
						<div class="circle"></div>
					</div>
					<div class="circle-clipper right">
						<div class="circle"></div>
					</div>
				</div>

				<div class="spinner-layer spinner-yellow">
					<div class="circle-clipper left">
						<div class="circle"></div>
					</div>
					<div class="gap-patch">
						<div class="circle"></div>
					</div>
					<div class="circle-clipper right">
						<div class="circle"></div>
					</div>
				</div>

				<div class="spinner-layer spinner-green">
					<div class="circle-clipper left">
						<div class="circle"></div>
					</div>
					<div class="gap-patch">
						<div class="circle"></div>
					</div>
					<div class="circle-clipper right">
						<div class="circle"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php } ?>	
<div class="spacer-xlarge"></div>
<!-- Modal Structure -->
<div id="modal-popup" class="modal bottom-sheet modal-popup-info">
	<div class="modal-content content-info">
	</div>
	<div class="modal-footer">
	</div>
</div>

<script type="text/javascript">

	
   $("select").formSelect();  
	
	$(".datepicker.datepicker7").datepicker({
		autoClose: true,
		format: "dd-mm-yyyy",
		autoClose: true
	 });
	 <?php if(!empty($this->arrFilter['startDate'])){?>
	$("#startDate").datepicker(
		"setDate","<?php echo date("m-d-Y", strtotime($this->arrFilter['startDate']));  ?>"
	 );
   <?php } ?>
     <?php if(!empty($this->arrFilter['endDate'])){?>
	 $("#endDate").datepicker(
		"setDate","<?php echo date("m-d-Y", strtotime($this->arrFilter['endDate']));  ?>"
	 );
	<?php } ?>
	<?php if(!empty($this->row)){?>
		var allRecord ='<?php echo $this->allRow; ?>';
		var stickyValue ='<?php echo $stickyBlog; ?>';
		var trackPage = 1;
		var check = 1;
   
		$(window).scroll(function() {
		   if($(window).scrollTop() + $(window).height() > $(document).height() - 1) {
			   if(check==1){
				   loadContents();
				}
		   }
		});
	
		function loadContents(){
			check=0;
			var urlMoreRow = '<?php echo $this->baseUrl().'/section/payment/morerecord/'.$querystring; ?>';
			$("#preLoadRecord").addClass("active");
			$.ajax({
				url:urlMoreRow,
				type: "post",
				data: {
					'page':trackPage
					,'stickyValue':stickyValue
				},
				dataType: "json",
				success: function(data){
					
					trackPage = data.trackPage;
					if(trackPage>allRecord){
					   trackPage = allRecord;
					   $('.recordMessage').html('');
						
					}else{
						$('.recordMessage').html('<?php echo $tr->translate("SCROLL_FOR_MORE_DATA");?>');
						setTimeout(function () {
							check = 1;
						}, 1000);
					}
					setTimeout(function () {
						$('#totalRecord').html(trackPage+' /'+allRecord);
						$("#listRecord").append(data.htmlRecord);
						stickyValue = data.stickyValue;
						$("#preLoadRecord").removeClass("active");
					}, 500);
					
				  
					
				},
				error: function(err) {
					alert(err);
				}
			});

		}
		
		function getPopupContent(payment){
			var urlRowContent = '<?php echo $this->baseUrl().'/section/payment/detailcontent'; ?>';
				$.ajax({
					url:urlRowContent,
					type: "post",
					data: {
						'id':payment
						
					},
					dataType: "json",
					success: function(data){
						
						$('.content-info').html(data.htmlRecord);
						setTimeout(function () {
								$('#modal-popup').modal('open');
						}, 500);
						
					},
					error: function(err) {
						alert(err);
					}
				});

		}
	
	<?php } ?>
</script>

