<?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage(1);
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	
	$key = new Application_Model_DbTable_DbKeycode();
	$dataInfo=$key->getKeyCodeMiniInv(TRUE);
	
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$currentLang = $dbGb->currentlang();
	$systemLink = $dbGb->systemLink();
	
	$clientTitle= $tr->translate("CUSTOMER_BRANCH");
	if(!empty($dataInfo['schooolNameKh'])){
		$clientTitle= $dataInfo['schooolNameKh'];
	}
	$clientTitleEn="";
	if(!empty($dataInfo['schooolNameEng'])){
		$clientTitleEn= $dataInfo['schooolNameEng'];
	}
	$defaultLogo = $this->baseUrl()."/images/Logo/Logo.png";
	if(!empty($dataInfo['logo'])){
		$logo = $systemLink.'/images/Logo/'.$dataInfo['logo'];
		if ($dbGb->does_url_exists($logo)){ 
			$defaultLogo = $systemLink.'/images/Logo/'.$dataInfo['logo'];
		}
	}
	
	$this->headTitle($clientTitle." / ".$clientTitleEn); 
	echo $this->headTitle();
	
	


$contact = $this->contact;
$contact['latitude'] = empty($contact['latitude'])?"11.594111046749918":$contact['latitude'];
$contact['longitude'] = empty($contact['longitude'])?"104.88356770859102":$contact['longitude'];

$allLang = $this->allLang;
?>
<div class="bgBodyhome"></div>	
<div class="bgWhite-for-list "></div>
<!-- START navigation -->
<nav class=" preLogin topbar navigation" role="navigation">
    <div class=" nav-wrapper container">
      <a id="logo-container" href="<?php echo $this->baseUrl()."/index"?>" class=" brand-logo " >
		<img class="logo-app" src="<?php echo $defaultLogo;?>" alt=""  />
	  </a>
	 

	  <!-- Modal Structure -->
      <div id="modalLanguage" class="modal bottom-sheet white dark-text">
        <div class="modal-content">
          <h4 class="text-center"><?php echo $tr->translate("CHOOSE_LANGUAGE"); ?></h4>
			<div class="row ">
                <div class="col s1 pad-0">
				</div>
                <div class="col s10 pad-0">
				  <div class="collection langList">
				   <?php 
					$imgLangeCurrent ="";
					if(!empty($allLang)) foreach($allLang AS $lang){ 
						if(!empty($lang['iconImage'])){
							$imgLange = $systemLink.'/images/'.$lang['iconImage'];
							if ($dbGb->does_url_exists($imgLange)){ 
								$imgLange = $systemLink.'/images/'.$lang['iconImage'];
								$iconCurrent="";
								$current="";
								if($currentLang==$lang['id']){
									$imgLangeCurrent = $imgLange;
									$iconCurrent = '<i class="mdi mdi-check-circle accent-text"></i>';
									$current="";
								}
					  ?>
					  <a onClick="changeLange(<?php echo $lang['id'];?>)" class="collection-item <?php echo $current;?>">
						<img class="languageImage" src="<?php echo $imgLange;?>" alt=""  />
						<?php echo $lang['title']." ".$iconCurrent; ?>
						</a>
					<?php }
				} ?>
		  <?php } ?>
					
					
				  </div>
				</div>
				<div class="col s1 pad-0">
				</div>
			</div>
        </div>
      </div>
      <a href="#modalLanguage" class="languageSwitch waves-effect waves-circle navicon right modal-trigger show-on-large pulse">
		<?php ?>
		<img class="languageSwitch" src="<?php echo $imgLangeCurrent;?>" alt=""  />
	  </a>

      
	  
    </div>
</nav>
 <div class="col s12 pad-0">
	<div class="index-carousel">
		<div class="carousel carousel-content carousel-slider center home-carousel">
			<?php if(!empty($this->slide)) foreach($this->slide AS $key => $slide ){?>
				<?php 	if(!empty($slide['images'])){ 
							$slideImg = $systemLink.'/images/slide/'.$slide['images'];
							if ($dbGb->does_url_exists($slideImg)){ 
							 
							?>
			<div class="carousel-item primary-bg white-text" style="background-image: url('<?php echo $slideImg; ?>')" href="#<?php echo $key; ?>!">
				<div class="item-content">
				</div>
			</div>
			<?php 			}
						} 
				} 
			?>
		</div> 
	</div> 
</div> 
<div class="container blog-tab-home">
	<div class="row ">
		<div class="col s12 pad-0">     
			<div class="row">
				<div class="col s12">
					<ul class="tabs z-depth-1 tabs-icons tab-home">
						<li class="tab col s3">
							<a href="#maintab1-8">
								<i class="mdi mdi-lightbulb-on-outline"></i>
								<span class="tab-title"><?php echo $tr->translate("INDRODUCTION"); ?></span>
							</a>
						</li>
						<li class="tab col s3">
							<a href="#maintab2-8">
								<i class="mdi mdi-clipboard-text"></i>
								<span class="tab-title"><?php echo $tr->translate("PROGRAM"); ?></span>
							</a>
						</li>
						<li class="tab col s3">
							<a href="#maintab3-8">
								<i class="mdi mdi-information-outline"></i>
								<span class="tab-title"><?php echo $tr->translate("ABOUTS"); ?></span>
							</a>
						</li>
					</ul>
				</div>
				<div id="maintab1-8" class="col s12 ">
				  <div class="tab-content tab-content-home ">
					<div class="section">
						<div class="row">
							<div class="text description primary-text"><?php echo $this->introductionHome['lbl_introduction']['title']; ?></div>
							<div class="intro-blog">
								<?php $introductionImage= $this->introductionHome['introduction_image']['title'];
									$introductionImage = $systemLink.'/images/newsevent/introduction_image/'.$introductionImage;
									if ($dbGb->does_url_exists($introductionImage)){ 
								?>
								<img class="intro-image" src="<?php echo $introductionImage;?>" alt=""  />
								<?php } ?>
								<a href="#modalHowtoUser" class='modal-trigger waves-light btn-large btn-rounded bg-darkyellow ploat-btn'>
									<i class="mdi mdi-play-circle-outline "></i> <?php echo $tr->translate("CLICK_HOW_TO_USE"); ?>
								</a>	
							</div>
							 <div class="text description primary-text"><?php echo $this->introductionHome['lbl_introduction_i']['title']; ?></div>
							<div class="center starting-btn">
								<strong><?php echo $tr->translate("CLICK_FOR_STARTING_USE"); ?></strong>
								<a href="<?php echo $this->baseUrl()."/index/login"?>" class='waves-light btn-large btn-rounded bg-darkyellow preloader-trigger'>
									<i class="mdi mdi-account-circle "></i> <?php echo $tr->translate("Get Started"); ?>
								</a>	
							</div>
							
						</div>
					</div>	
				  </div>
				</div>
				<div id="maintab2-8" class="col s12">
				
					<?php if(!empty($this->course)){?>
						<div class="row">
							<div class="col s12">
								<ul class="tabs blue-bg colored tab-course ">
									<?php foreach($this->course AS $key => $course){?>
									<li class="tab col s6">
										<a href="#program<?php echo $key; ?>-8"  >
											<?php echo $course['title']; ?>
										</a>
									</li>
									<?php } ?>
									
								</ul>
							</div>
							<?php foreach($this->course AS $key => $course){?>
								<div id="program<?php echo $key; ?>-8" class="col s12 <?php if($key==0){ echo 'active';}?>">
									<div class="tab-content tab-content-home ">
										<h5 class="center bot-20 sec-tit sectionTitle"><?php echo $course['title']; ?></h5>
										<div class="text description primary-text tab-detail"><?php echo $course['description']; ?></div>
									</div>
								</div>
								<?php } ?>
						</div>
						<?php } ?>
					
				</div>
				<div id="maintab3-8" class="col s12 ">
					<div class="tab-content tab-content-home">
						<?php if(!empty($this->aboutUs)){ foreach($this->aboutUs AS $aboutUs){?>
							<div class="section">
								<div class="container">
									<div class="row">
										<div class="spacer"></div>
										<h5 class="center bot-20 sec-tit sectionTitle"><?php echo $aboutUs['title']; ?></h5>
										
										<div class="text description"><?php echo $aboutUs['description']; ?></div>
									</div>
								</div>
							</div>
						<?php } }?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="center index-start">
	<a href="<?php echo $this->baseUrl()."/index/login"?>" class='waves-light btn-large bg-primary preloader-trigger'>
		<i class="mdi mdi-account-circle "></i> <?php echo $tr->translate("Get Started"); ?>
	</a>	
</div>
<footer class="page-footer">
    <div class="container footer-content">
      <div class="row">
        <div class="">
          <h5 class="logo"><?php echo $tr->translate("CONTACT_AND_ADDRESS"); ?></h5>
        </div>
		<div class="map-wrap">
			<iframe 
			  width="300" 
			  height="170" 
			  frameborder="0" 
			  scrolling="no" 
			  marginheight="0" 
			  marginwidth="0" 
			  src="https://maps.google.com/maps?q=<?PHP  echo $contact['latitude']; ?>,<?PHP  echo $contact['longitude']; ?>&hl=kh&z=14&amp;output=embed"
			 >
			</iframe>
		</div>
        <div class="link-wrap">
          <ul class="link-ul">
			<li><a class="" href="#!"><i class="mdi mdi-map-marker"></i> <?PHP  echo strip_tags($contact['description']); ?></a></li>
            <li><a class="" href="tel:<?PHP  echo $contact['phone']; ?>"><i class="mdi mdi-phone"></i> <?PHP  echo $contact['phone']; ?></a></li>
            <li><a class="" href="mailto:<?PHP  echo $contact['email']; ?>"><i class="mdi mdi-email"></i> <?PHP  echo $contact['email']; ?></a></li>
            <li><a class="" target="_blank" href="<?PHP  echo $contact['website']; ?>"><i class="mdi mdi-web"></i> <?PHP  echo $contact['website']; ?></a></li>
           </ul>
            <ul class="social-wrap">
            <li class="social">
			<?php if(!empty($contact['facebook'])){?>
              <a class="facebook" href="<?PHP  echo $contact['facebook']; ?>"><i class="mdi mdi-facebook"></i></a>
			<?php } ?>
			<?php if(!empty($contact['other_social'])){?>
              <a class="messenger" href="<?PHP  echo $contact['other_social']; ?>"><i class="mdi mdi-facebook-messenger"></i></a>
			<?php } ?>
			<?php if(!empty($contact['youtube'])){?>
              <a class="youtube" href="<?PHP  echo $contact['youtube']; ?>"><i class="mdi mdi-youtube"></i></a>
			<?php } ?>
			
			<?php if(!empty($contact['instagram'])){?>
              <a class="telegram" href="<?PHP  echo $contact['instagram']; ?>"><i class="mdi mdi-telegram"></i></a>
			<?php } ?>
			
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      &copy; <?php echo $tr->translate("Developed By"); ?> <a class="" href="http://www.cam-app.com/"><?php echo $tr->translate("CAMAPP_TECHNOLOGY"); ?></a>
      </div>
    </div>
</footer>

 <!-- Modal Structure -->
  <div id="modalHowtoUser" class="modal white dark-text">
	<div class="modal-content">
	  <h5 class="center bot-20 sec-tit sectionTitle"><?php echo $tr->translate("HOW_TO_USE"); ?></h5>
		<div class="row ">
			<?php $video_id = $this->introductionHome['lbl_howtouse']['title']; ?>
			<div class="col s12 pad-0">
				<div class="youTubeBlog" >
					<iframe src="http://www.youtube.com/embed/<?php echo $video_id;?>?rel=0&amp;autoplay=1&mute=1&loop=1" frameborder="0" style="position:absolute;width:100%;height:100%;left:0"  allowfullscreen></iframe>
				</div>
			</div>
			
		</div>
	</div>
  </div>
<script>
$(".tabs").tabs();
</script>

	
















