 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("ATTENDANCE_POLICY"));
	echo $this->headTitle();
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$systemLink = $dbGb->systemLink();
	
?>
<div class="bgBodyhome"></div>	
<div class="bgWhite-for-list "></div>
<div class="bgBody-listview gradientBluePrimary">
	<div class="container">
		<div class="section">
			<div class="row">
				<div class="col s12 pad-0 blog-page-title">
					<div class="page-icon">
						<i class="mdi mdi-account-multiple-check "></i>
					</div>
					<h5 class="sec-page-tit  ">
						<?php echo $tr->translate("ATTENDANCE_POLICY"); ?>
					</h5>
				</div>
			</div>
		</div>
	</div>
</div>
<?php if(!empty($this->rs)){ foreach($this->rs AS $row){?>	
 <div class="container">
	<div class="section">
		<div class="row">
			<div class="spacer"></div>
			<h5 class=" bot-20 sec-tit sectionTitle"><?php echo $row['title']; ?></h5>
			<div class="text description"><?php echo $row['description']; ?></div>
		</div>
	</div>
</div>
<?php } }?>
<div class="spacer-xlarge"></div>


