 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("DASHBOARD"));
	echo $this->headTitle();
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$currentlang = $dbGb->currentlang();
	$systemLink = $dbGb->systemLink();
	
?>
<div class="bgBody"></div>	
<div class="carousel carousel-content carousel-slider center home-carousel">
	<?php if(!empty($this->slide)) foreach($this->slide AS $key => $slide ){?>
		<?php 	if(!empty($slide['images'])){ 
					$slideImg = $systemLink.'/images/slide/'.$slide['images'];
					if ($dbGb->does_url_exists($slideImg)){ 
					 
					?>
	<div class="carousel-item primary-bg white-text" style="background-image: url('<?php echo $slideImg; ?>')" href="#<?php echo $key; ?>!">
		<div class="item-content">
		</div>
	</div>
	<?php 			}
				} 
		} 
	?>
</div>

<div class="boxDashboard">
	<div class="container">
		<div class="section">
			<div class="row mrg-0">
				<div class="col s12 pad-0">
					<div class="row settings-row">
						<div class="col s4">
							<div class="setting-box center">
								<a class="waves-effect preloader-trigger" href="<?php echo $this->baseUrl()."/section/score";?>">
									<div class="icon-block ">
										<div class="center iconscore"></div>
										<h6 class="center "><?php echo $tr->translate("STUDY_RESULT"); ?></h6>
									</div>
								</a>
						  </div>
						</div>
						<div class="col s4">
							<div class="setting-box center">
								<a class="waves-effect preloader-trigger" href="<?php echo $this->baseUrl()."/section/schedule";?>">
									<div class="icon-block ">
										<div class="center iconschedule"></div>
										<h6 class="center "><?php echo $tr->translate("SCHEDULE"); ?></h6>
									</div>
								</a>
						  </div>
						</div>
						<div class="col s4">
							<div class="setting-box center">
								<a class="waves-effect preloader-trigger" href="<?php echo $this->baseUrl()."/section/attendance";?>">
									<div class="icon-block ">
										<div class="center iconatt"></div>
										<h6 class="center "><?php echo $tr->translate("ATTENDENCE_RECORD"); ?></h6>
									</div>
								</a>
						  </div>
						</div>
						<div class="col s4">
							<div class="setting-box center">
								<a class="waves-effect preloader-trigger" href="<?php echo $this->baseUrl()."/section/mistake";?>">
									<div class="icon-block ">
										<div class="center icondiscipline"></div>
										<h6 class="center "><?php echo $tr->translate("DISCIPLINE"); ?></h6>
									</div>
								</a>
						  </div>
						</div>
						<div class="col s4">
							<div class="setting-box center">
								<a class="waves-effect preloader-trigger" href="<?php echo $this->baseUrl()."/section/payment";?>">
									<div class="icon-block ">
										<div class="center iconpayment"></div>
										<h6 class="center "><?php echo $tr->translate("PAYMENT_HISTORY"); ?></h6>
									</div>
								</a>
						  </div>
						</div>
						<div class="col s4">
							<div class="setting-box center">
								<a class="waves-effect preloader-trigger" href="<?php echo $this->baseUrl()."/section/course";?>">
								<div class="icon-block ">
									<div class="center iconcourse"></div>
									<h6 class="center "><?php echo $tr->translate("PROGRAM"); ?></h6>
								</div>
							  </a>
						  </div>
						</div>
						
						<div class="col s4">
							<div class="setting-box center">
								<a class="waves-effect preloader-trigger" href="<?php echo $this->baseUrl()."/section/calendar";?>">
									<div class="icon-block ">
										<div class="center iconcalendar"></div>
										<h6 class="center "><?php echo $tr->translate("CALENDAR"); ?></h6>
									</div>
								</a>
						  </div>
						</div>
						<div class="col s4">
							<div class="setting-box center">
								<a class="waves-effect preloader-trigger" href="<?php echo $this->baseUrl()."/utility/news";?>">
									<div class="icon-block ">
										<div class="center iconnews"></div>
										<h6 class="center "><?php echo $tr->translate("NEWS_EVENT"); ?></h6>
									</div>
								</a>
						  </div>
						</div>
						<div class="col s4">
							<div class="setting-box center">
								<a class="waves-effect preloader-trigger" href="<?php echo $this->baseUrl()."/utility/aboutus";?>">
								<div class="icon-block ">
									<div class="center iconabout"></div>
									<h6 class="center "><?php echo $tr->translate("ABOUTS"); ?></h6>
								</div>
							  </a>
						  </div>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php if(!empty($this->rowScore)){  ?>
<div class="home-list score-list-info ">
	<div class="container">
		<div class="row mrg-0">
			<div class="col s12 pad-0">
				<h5 class="bot-20 sec-tit  "><?php echo $tr->translate("LATEST_SCORE"); ?>
				<!--
				<a class="waves-effect waves-light btn btn-rounded lighten-2 view-all" href="#!">
					<?php //echo $tr->translate("VIEW_ALL"); ?>
				</a>
				-->
			</h5>
				<?php foreach($this->rowScore AS $score){?>
				
				<?php 
					$rank = $score['rank']; 
					$forMonthTitle = $score['forMonthTitle']; 
					
					$academicYearTitle = $score['academicYearTitle']; 
					$totalScore = $score['totalScore'];
					$totalAvg = $score['totalAvg'];
					$amountStudent = sprintf('%02d',$score['amountStudent']);
					
					if($currentlang==1){
						$rank = $dbGb->getNumberInkhmer($rank);
						$forMonthTitle = $dbGb->getNumberInkhmer($forMonthTitle);
						$academicYearTitle = $dbGb->getNumberInkhmer($academicYearTitle);
						
						$totalScore = $dbGb->getNumberInkhmer($totalScore);
						$totalAvg = $dbGb->getNumberInkhmer($totalAvg);
						$amountStudent = $dbGb->getNumberInkhmer($amountStudent);
					}
				?>
				
				<div class="ui-grids scoreList">
					<div class="row ">
						<div class="col s7 blg-score-left">
							<h3 class="title-score"><?php echo $score['forTypeTitle']; ?> <strong class="mark-title"><?php echo $forMonthTitle; ?></strong> </h3>
							<span class="score-info"><strong class="mark-title"><?php echo $academicYearTitle; ?></strong></span>
							<span class="score-info"><?php echo $tr->translate("CLASS_NAME"); ?> <strong class="mark-title"><?php echo $score['groupCode']; ?></strong></span>
							<span class="score-info"><?php echo $tr->translate("TEACHER"); ?> <strong class="mark-title"><?php echo $score['teacherName']; ?></strong></span>
							<span class="score-info"><?php echo $tr->translate("AMT_STUDENT"); ?> <strong class="mark-title"><?php echo $amountStudent." ".$tr->translate("STU_UNIT"); ?></strong></span>
							</div>
						<div class="col s5 blg-score-right">
							<h2 class="ranking"><?php echo $rank; ?></h2>
							<span class="score-info"><?php echo $tr->translate("TOTAL_SCORE"); ?> <strong class="mark-title"><?php echo $totalScore; ?></strong></span>
							<span class="score-info"><?php echo $tr->translate("AVERAGE"); ?> <strong class="mark-title"><?php echo $totalAvg; ?></strong></span>
							<div class="spacer-small"></div>
							<div class="spacer-small"></div>
							<a class="waves-effect waves-light btn btn-rounded  lighten-2 preloader-trigger" onClick="getPopupContent(<?php echo $score['id'];?>);">
								<?php echo $tr->translate("MORE_DETAIL"); ?>
							</a>
						</div>
					</div>
				</div>
				<?php } ?>
				<div class="spacer-xlarge"></div>
			</div>
		</div>
	</div>
</div>
<div id="modal-popup" class="modal bottom-sheet modal-popup-info">
	<div class="modal-content content-info">
		
	</div>
	
</div>
<?php } ?>
<!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - START --> 
<script type="text/javascript">
  $(document).ready(function(){
     

     $(".carousel-content.carousel-slider").carousel({
        fullWidth: true,
        indicators: true
      }).css("height", 200);

  });   
  <?php if(!empty($this->rowScore)){ ?>
		
	
	function getPopupContent(scoreKey){
		
		var urlDetailContent = '<?php echo $this->baseUrl().'/section/score/detailcontent'; ?>';
			$.ajax({
				url:urlDetailContent,
				type: "post",
				data: {
					'id':scoreKey
				},
				dataType: "json",
				success: function(data){
					
					$('.content-info').html(data.htmlRecord);
					setTimeout(function () {
							$('#modal-popup').modal('open');
					}, 500);
					$('.preloader-background').delay(10).fadeOut('slow');
					
				},
				error: function(err) {
					$('.preloader-background').delay(10).fadeOut('slow');
					alert(err);
				}
			});

	}
	<?php } ?>
  </script><!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - END --> 

