<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("CALENDAR"));
	echo $this->headTitle();
?>

<!doctype html>
<html lang="en">
  <head>
  	<title>Calendar 07</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/templates/calendar/css/style.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/templates/assets/css/style.css">
	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="elegant-calencar d-md-flex">
						<div class="wrap-header d-flex align-items-center img" style="background-image: url(<?php echo $this->baseUrl();?>/templates/calendar/images/bg.jpg);">
				      <p id="reset">Today</p>
			        <div id="header" class="p-0">
		            <div class="head-info">
		            	<div class="head-month"></div>
		                <div class="head-day"></div>
		            </div>
			        </div>
			      </div>
			      <div class="calendar-wrap">
			      	<div class="w-100 button-wrap">
				      	<div class="pre-button d-flex align-items-center justify-content-center"><i class="fa fa-chevron-left"></i></div>
				      	<div onclick="alert(222);"id="nextBtn" class="next-button d-flex align-items-center justify-content-center"><i class="fa fa-chevron-right"></i></div>
			      	</div>
			        <table id="calendar">
		            <thead>
		                <tr>
	                    <th><?php echo $tr->translate('Sun');?></th>
	                    <th><?php echo $tr->translate('Mon');?></th>
	                    <th><?php echo $tr->translate('Tue');?></th>
	                    <th><?php echo $tr->translate('Wed');?></th>
	                    <th><?php echo $tr->translate('Thu');?></th>
	                    <th><?php echo $tr->translate('Fri');?></th>
	                    <th><?php echo $tr->translate('Sat');?></th>
		                </tr>
		            </thead>
		            <tbody>
	                <tr>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                </tr>
	                <tr>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                </tr>
	                <tr>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                </tr>
	                <tr>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                </tr>
	                <tr>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                </tr>
	                <tr>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                  <td></td>
	                </tr>
		            </tbody>
			        </table>
			      </div>
			      
			     
			    </div>
			    <div class="row ">
			     	<div class="calendar-wrap">
			                <div class="col s12 pad-0"><h5 class="bot-20 sec-tit  "><?php echo $tr->translate('PUBLIC_HOLIDAY_CEREMONY')?></h5>            
					    		<ul class="events">
					                <li class="event-item card">
					                  <div class="time">ទិវាចូលឆ្នាំសកល Happy New Year</div>
					                    <span class="new badge blue lighten-2" data-badge-caption="">Monday
					                    <span class="daycolor" data-badge-caption="">09</span>
					                    </span>
					                    
					                  <div class="actions">
					                        <a href="ui-app-newevent.html" class='waves-effect'>                          <i class="mdi mdi-square-edit-outline"></i>
					                        </a>                        <a href="#!"><i class="mdi mdi-delete"></i></a>
					                  </div>
					                </li>
					     	</ul>
				    		</div>
				   		</div>
			     </div>
				</div>
				 <div id="value"> Value here</div>
			</div>
			
			<a href="<?php echo $this->baseUrl()."/index/"?>" class='waves-effect preloader-trigger'>
					<i class="mdi mdi-backup-restore"></i> <?php echo $tr->translate("BACK_HOME");?>
				</a>      
		</div>
	</section>

	<script src="<?php echo $this->baseUrl();?>/templates/calendar/js/jquery.min.js"></script>
    <script src="<?php echo $this->baseUrl();?>/templates/calendar/js/popper.js"></script>
  <script src="<?php echo $this->baseUrl();?>/templates/calendar/js/bootstrap.min.js"></script>
  <script src="<?php echo $this->baseUrl();?>/templates/calendar/js/main.js"></script>

	</body>
	<script type="text/javascript">
		
		function callHoliday() {
		  alert('abc');
		}
</script>
</html>



