<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("CALENDAR"));
	echo $this->headTitle();
?>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/templates/calendar/css/style.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/templates/assets/css/style.css">
	</head>
	
	<section class="ftco-section">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="elegant-calencar d-md-flex">
						<div class="wrap-header d-flex align-items-center img" style="background-image: url(<?php echo $this->baseUrl();?>/templates/calendar/images/bg.jpg);">
				      <p id="reset">Today</p>
			        <div id="header" class="p-0">
		            <div class="head-info">
		            	<div class="head-month"></div>
		                <div class="head-day"></div>
		            </div>
			        </div>
			      </div>
			      <div class="calendar-wrap">
			      	<div class="w-100 button-wrap">
				      	<div class="pre-button d-flex align-items-center justify-content-center"><i class="fa fa-chevron-left"></i></div>
				      	<div onclick="getAllHoliday(0);" id="nextBtn" class="next-button d-flex align-items-center justify-content-center"><i class="fa fa-chevron-right"></i></div>
			      	</div>
			        <table id="calendar">
			            <thead>
			                <tr>
		                    <th><?php echo $tr->translate('Sun');?></th>
		                    <th><?php echo $tr->translate('Mon');?></th>
		                    <th><?php echo $tr->translate('Tue');?></th>
		                    <th><?php echo $tr->translate('Wed');?></th>
		                    <th><?php echo $tr->translate('Thu');?></th>
		                    <th><?php echo $tr->translate('Fri');?></th>
		                    <th><?php echo $tr->translate('Sat');?></th>
			                </tr>
			            </thead>
			            <tbody>
		                <tr>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                </tr>
		                <tr>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                </tr>
		                <tr>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                </tr>
		                <tr>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                </tr>
		                <tr>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                </tr>
		                <tr>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                  <td></td>
		                </tr>
			            </tbody>
			        </table>
			      </div>
			    </div>
			    
			   	 <div class="row ">
			                <div class="col s12 pad-0"><h5 class="bot-20 sec-tit  "><?php echo $tr->translate('PUBLIC_HOLIDAY_CEREMONY')?></h5>            
					    		<ul id="holidayList" class="collection invoice-item">
					     		</ul>
				    		</div>
				    		
			     	</div>
			     	
				</div>
			</div>
			
			<a href="<?php echo $this->baseUrl()."/index/"?>" class='waves-effect preloader-trigger'>
					<i class="mdi mdi-backup-restore"></i> <?php echo $tr->translate("BACK_HOME");?>
				</a>      
		</div>
	</section>
	<!-- Modal Structure -->
<div id="modal-popup" class="modal bottom-sheet modal-popup-info">
	<div class="modal-content content-info">
	</div>
	<div class="modal-footer">
	</div>
</div>
	<?php $baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl(); ?>
	<!--<script src="<?php echo $this->baseUrl();?>/templates/calendar/js/jquery.min.js"></script>
	 <script src="<?php echo $this->baseUrl();?>/templates/calendar/js/bootstrap.min.js"></script> -->
    <script src="<?php echo $this->baseUrl();?>/templates/calendar/js/popper.js"></script>
  
  <script src="<?php echo $this->baseUrl();?>/templates/calendar/js/main.js"></script>

	</body>
	<script type="text/javascript">
		
		function getAllHoliday(month){
			holidayList='';
			$("#holidayList").empty();
			if(month==0){
				return false;
			}
			
			var url = '<?php echo $this->url(array('module'=>'section','controller'=>'calendar','action'=>'getholiday'));?>';
		    	$.ajax({
					url:url,
					type: "post",
					data: {
						'url':'getholiday',
						'mothHoliday':month,
						'currentLang':'1',
					},
					dataType: "json",
					success: function(data){
						for(i=0;i<data.length;i++){
					    		holidayList+='<li class="collection-item avatar">';
					    		holidayList+='<div class="item-det"><span class="title">'+data[i].holiday_name+'</span></div>';
					    		holidayList+='<div class="secondary-content"><h6 class="top-0">'+data[i].holiday_day+'<br />'+data[i].holiday_string+'</h6></div>';
					    		holidayList+='</div></li>';

					    		/*<li class="collection-item avatar">
					              <div class="item-det">
					                  <span class="title">Wenasdf asdf asdfa sdf asdf asdf asdflkasdlkfjasdklfa s</span>
					              </div>
					                <div class="secondary-content">
					                    <h6 class="top-0">Wed<br /> 01</h6>
					                </div>
					            </li>*/
					            
						}
						 $("#holidayList").append(holidayList);
						
					},
					error: function(err) {
						alert('err'+err);
						console.log(err);
						
					}
				});
		    }

		</script>
</html>



