 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("SCHEDULE"));
	echo $this->headTitle();
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$systemLink = $dbGb->systemLink();
	
?>
<div class="bgBodyhome"></div>	
<div class="bgBody-listview gradientBlue">
	<div class="container">
			<div class="section">
				<div class="row">
					<div class="col s12 pad-0 blog-page-title">
						<div class="page-icon">
							<i class="mdi mdi-calendar-clock "></i>
						</div>
						<h5 class="sec-page-tit  ">
							<?php echo $tr->translate("SCHEDULE"); ?>
						</h5>
						<span class="sec-page-desc">
							ចំណាត់ថ្នាក់ប្រចាំខែ និងប្រចាំឆមាស, ព្រឹត្តិប័ត្តពិន្ទុ, និងលិខិតផ្សេៗ...
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="main-page-list">
	<div class="bl-schedule-list-row ">
		<div class="spacer-small"></div>
		<div class="spacer-medium"></div>
		<?php $stickyBlog="";  if(!empty($this->row)){ foreach($this->row AS $schedule){?>
		<?php if($stickyBlog!=$schedule['day_id']){?>
		<div class="stickyBlog">
			<div class="stickyTitle">
				<h3 class="title-day"><?php echo $schedule['dayTitle']; ?></h3>
			</div>
		</div>
		<?php } $stickyBlog =$schedule['day_id']; ?>
		<div class="container">
			<div class="row mrg-0">
				<div class="col s12 pad-0">
					<div class="ui-grids scheduleList">
						<div class="row schedule-row mrg-0">
							<div class="col s4 blg-schedule-left">
								
								<span class="time-schedule"><?php echo $schedule['fromHourTitle']; ?></span>
								<span class="time-schedule">-</span>
								<span class="time-schedule"><?php echo $schedule['toHourTitle']; ?></span>
							</div>
							<div class="col s8 blg-schedule-right">
								<h2 class="subject-title"><?php echo $schedule['subjectTitle']; ?></h2>
								<span class="schedule-info teacher-name"><?php echo $tr->translate("TEACHER"); ?> <strong class="mark-title"><?php echo $schedule['teaccherName']; ?></strong></span>
								<div class="row mrg-0">
									<div class="col s6">
										<span class="schedule-info"><?php echo $tr->translate("CLASS_NAME"); ?> <strong class="mark-title"><?php echo $schedule['groupCode']; ?></strong></span>
									</div>
									<div class="col s6">
										<span class="schedule-info"><?php echo $tr->translate("ROOM"); ?> <strong class="mark-title"><?php echo $schedule['roomName']; ?></strong></span>
									</div>
								</div>
							</div>
						</div>
					</div>
					
				</div>
			</div>
		</div>
		<?php } ?>
		<?php } ?>
		
		<div class="spacer-xlarge"></div>
	</div>
</div>



