 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$currentlang = $dbGb->currentlang();
	
	$row = $this->row;
	$rowDetail = $this->rowDetail;
	
	$this->headTitle($tr->translate("MISTAKE_DETAIL"));
	echo $this->headTitle();
	
	$yearAtt = date("Y",strtotime($row['date_attendence'])); 
	$monthAtt = date("M",strtotime($row['date_attendence'])); 
	$monthKey = date("m",strtotime($row['date_attendence'])); 
	if($currentlang==1){
		$yearAtt = $dbGb->getNumberInkhmer($yearAtt);
		$monthAtt = $dbGb->getMonthInkhmer($monthKey);
	}
	
?>
<div class="bgBodyhome"></div>	

<div class="bgWhite-for-list "></div>
<div class="bgBody-listview bluePrimary page-detail-head-blg">
	
</div>
<div class="page-detail-title-blg">
	<div class="container">
		<div class="section">
			<div class="card-panel bg-white panel-bluePrimary">
				<h5 class="title-detial top-0">
					<?php echo $tr->translate("MISTAKE_DETAIL"); ?>​
				</h5>
				<div class="row mrg-0">
					<div class="col s9 ">
						<span class="main-detail-info "><?php echo $tr->translate("CLASS_NAME"); ?> <strong class="mark-title"><?php echo $row['groupCode']; ?></strong></span>
						<span class="main-detail-info "><?php echo $tr->translate("ACADEMIC_YEAR"); ?> <strong class="mark-title"><?php echo $row['academicYear']; ?></strong></span>
						<span class="main-detail-info "><?php echo $tr->translate("TEACHER"); ?> <strong class="mark-title"><?php echo $row['teacherName']; ?></strong></span>
					</div>
					<div class="col s3 flex-col">
						<h3 class="title-main-val ">
							<?php echo $monthAtt; ?>
							<span class="main-detail-info "><?php echo $yearAtt; ?></span>
						</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<?php if(!empty($rowDetail)){?>
<div class="spacer-small"></div>
<div class="items-info">
	<div class="container">
		<?php $i=0; foreach($rowDetail AS $rowVal){ $i++; ?>
			<?php 
				$num = $i; 
				if($currentlang==1){
					$num = $dbGb->getNumberInkhmer($i);
				}
			?>
			<div class="ui-grids lists-view-icon att-detial">
				<div class="row lists-view-icon-row  mrg-0">
					<div class="col s4 blg-row-left">
						<span class="title-flex">
							<?php echo $rowVal['attendenceStatusTitle']; ?>
						</span>
					</div>
					<div class="col s8 blg-row-right">
						<h2 class="main-title"><i class="mdi mdi-calendar-clock "></i> <?php echo date("d-m-Y",strtotime($rowVal['date_attendence'])); ?></h2>
						<span class="row-items-info"><?php echo $rowVal['description']; ?></span>
					</div>
				</div>
			</div>
			
		
			
			<?php } ?>
	</div>
</div>
<?php } ?>
<div class="spacer-medium"></div>

<div class="spacer-xlarge"></div>



