 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("DISCIPLINE"));
	echo $this->headTitle();
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$systemLink = $dbGb->systemLink();
	$currentlang = $dbGb->currentlang();
	
	$frm = $this->formFilter;
	$querystring = $this->queryString;
	$tSmall 	=0;
	$tMedium	=0;
	$tBig 		=0;
	$tOther 	=0;
?>
<div class="bgBodyhome"></div>	

<div class="bgBody-listview gradientBlue">
	<div class="container">
			<div class="section">
				<div class="row">
					<div class="col s12 pad-0 blog-page-title">
						<div class="page-icon">
							<i class="mdi mdi-medal "></i>
						</div>
						<h5 class="sec-page-tit  ">
							<?php echo $tr->translate("DISCIPLINE"); ?>
						</h5>
						<span class="sec-page-desc">
							<?php echo $tr->translate("DISCIPLINE_PAGE_DESC"); ?>
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="main-page-list">
	<div class="bl-mistake-list-row ">
		<div class="spacer-medium"></div>
		<div class="spacer-medium"></div>
		<div class="container">
			<div class="row mrg-0">
				<div class="col s12 pad-0">
					<div id="listRecord" class="ui-grids lists-view-icon envaluation">
					<?php if(!empty($this->row)){ 
						foreach($this->row AS $attedance){
							
							$yearAtt = date("Y",strtotime($attedance['date_attendence'])); 
							$monthAtt = date("M",strtotime($attedance['date_attendence'])); 
							$monthKey = date("m",strtotime($attedance['date_attendence'])); 
							
							$academicYear = $attedance['academicYear']; 
							
							$countSmallMistake 		= sprintf('%02d',$attedance['countSmallMistake']);
							$countMediumMistake 	= sprintf('%02d',$attedance['countMediumMistake']);
							$countBigMistake 			= sprintf('%02d',$attedance['countBigMistake']);
							$countOtherMistake 	= sprintf('%02d',$attedance['countOtherMistake']);
							
							if($currentlang==1){
								$academicYear = $dbGb->getNumberInkhmer($academicYear);
								$yearAtt = $dbGb->getNumberInkhmer($yearAtt);
								$monthAtt = $dbGb->getMonthInkhmer($monthKey);
								
								$countSmallMistake = $dbGb->getNumberInkhmer($countSmallMistake);
								$countMediumMistake = $dbGb->getNumberInkhmer($countMediumMistake);
								$countBigMistake = $dbGb->getNumberInkhmer($countBigMistake);
								$countOtherMistake = $dbGb->getNumberInkhmer($countOtherMistake);
							}
							
							$tSmall 	=$tSmall+$attedance['countSmallMistake'];
							$tMedium	=$tMedium+$attedance['countMediumMistake'];
							$tBig 		=$tBig+$attedance['countBigMistake'];
							$tOther 	=$tOther+$attedance['countOtherMistake'];
						?>
						<div class="row lists-view-icon-row  mrg-0">
							<div class="col s3 blg-row-left">
								<span class="title-flex">
									<?php echo $monthAtt; ?>	
									<span class="title-flex-sub"><?php echo $yearAtt; ?></span>
								</span>
							</div>
							<div class="col s9 blg-row-right">
								<div class="row mrg-0 info-blg">
									<div class="col s6">
										<span class="row-items-info"><?php echo $tr->translate("CLASS_NAME"); ?> <strong class="mark-title"><?php echo $attedance['groupCode']; ?></strong></span>
										<span class="row-items-info"><?php echo $tr->translate("ACADEMIC_YEAR"); ?> <strong class="mark-title"><?php echo $academicYear; ?></strong></span>
										<span class="row-items-info"><?php echo $tr->translate("ROOM"); ?> <strong class="mark-title"><?php echo $attedance['roomName']; ?></strong></span>
										<a class="waves-effect waves-light btn btn-rounded  lighten-2" onClick="getPopupContent(<?php echo $attedance['yearMonth']; ?>,<?php echo $attedance['group_id']; ?>)" >
											<?php echo $tr->translate("MORE_DETAIL"); ?>
										</a>
									</div>
									<div class="col s3">
										<span class="row-items-info text-right"><?php echo $tr->translate("SMALL_MISTACK"); ?></span>
										<span class="row-items-info text-right"><?php echo $tr->translate("MEDIUM_MISTACK"); ?></span>
										<span class="row-items-info text-right"><?php echo $tr->translate("BIG_MISTACK"); ?></span>
										<span class="row-items-info text-right"><?php echo $tr->translate("OTHER"); ?></span>
									</div>
									<div class="col s3">
										<span class="row-items-info counting text-right "><strong class="mark-title"><?php echo $countSmallMistake." ".$tr->translate("TIME_UNIT"); ?></strong></span>
										<span class="row-items-info counting text-right "><strong class="mark-title"><?php echo $countMediumMistake." ".$tr->translate("TIME_UNIT"); ?></strong></span>
										<span class="row-items-info counting text-right "><strong class="mark-title"><?php echo $countBigMistake." ".$tr->translate("TIME_UNIT"); ?></strong></span>
										<span class="row-items-info counting text-right "><strong class="mark-title"><?php echo $countOtherMistake." ".$tr->translate("TIME_UNIT"); ?></strong></span>
									
									</div>
								</div>
								
								
								
									
							</div>
						</div>
						
					<?php } ?>
				<?php } ?>
					</div>
					
					
				</div>
			</div>
		</div>
		
		<?php if(count($this->row)<$this->allRow){ ?>
		<div class="ui-grids ">
			<div class="row mrg-0">
				<div class="col s12 center " >
					<p id="totalRecord" class="total-record"><?php echo count($this->row)."/".$this->allRow; ?></p>
					<h3 class="title-empty recordMessage"><?php echo $tr->translate("SCROLL_FOR_MORE_DATA"); ?></h3>
				</div>
			</div>
			<div class="row mrg-0">
				<div class="col s12 center valign-wrapper" style="height: 100px;">
					<div id="preLoadRecord" class="preloader-wrapper small ">
						<div class="spinner-layer spinner-blue">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>

						<div class="spinner-layer spinner-red">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>

						<div class="spinner-layer spinner-yellow">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>

						<div class="spinner-layer spinner-green">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<?php } ?>
		<div class="spacer-xlarge"></div>
		
	</div>
	
		
</div>
<!-- Modal Structure -->
<div id="modalFilter" class="modal bottom-sheet white dark-text">
	<div class="modal-content">
		<div class="container">
			<div class="section ui-select">
				<form method="GET">
					<div class="row ">
						<div class="col s12 pad-0"><h5 class="bot-20 sec-tit  "><?php echo $tr->translate("FILTER"); ?></h5>        
							<div class="row">
								<div class="input-field  col s12">
									<?php echo $frm->getElement('academicYear');?>
								  <label><?php echo $tr->translate("ACADEMIC_YEAR"); ?></label>
								</div>
								<div class="input-field colLeft col s6">
									<?php echo $frm->getElement('forSemester');?>
								  <label><?php echo $tr->translate("SEMESTER"); ?></label>
								</div>
								<div class="input-field  colRight col s6">
									<?php echo $frm->getElement('month');?>
								  <label><?php echo $tr->translate("MONTH"); ?></label>
								</div>
								
								<div class="input-field  col s12">
									<button type="submit" class="fullsize waves-effect waves-light btn btn-rounded primary lighten-2 preloader-trigger" name="search"><?php echo $tr->translate("SEARCH"); ?></button>
								</div>
							</div>
							
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php 
$tSmallLB 		= sprintf('%02d',$tSmall);
$tMediumLB 	= sprintf('%02d',$tMedium);
$tBigLB 			= sprintf('%02d',$tBig);
$tOtherLB 	= sprintf('%02d',$tOther);


if($currentlang==1){
	$tSmallLB 	= $dbGb->getNumberInkhmer($tSmallLB);
	$tMediumLB 	= $dbGb->getNumberInkhmer($tMediumLB);
	$tBigLB 	= $dbGb->getNumberInkhmer($tBigLB);
	$tOtherLB 	= $dbGb->getNumberInkhmer($tOtherLB);
}
?>
<div class="total-page-footer total-total">
	<div class="container">
		<div class="row mrg-0 ">
			<div class="col s3 text-center">
				<span class="page-footer-info"><?php echo $tr->translate("SMALL_MISTACK"); ?></span>
				<span class="page-footer-info"><strong><?php echo $tSmallLB;?></strong></span>
			</div>
			<div class="col s3 text-center">
				<span class="page-footer-info"><?php echo $tr->translate("MEDIUM_MISTACK"); ?></span>
				<span class="page-footer-info"><strong><?php echo $tMediumLB;?></strong></span>
			</div>
			<div class="col s3 text-center">
				<span class="page-footer-info"><?php echo $tr->translate("BIG_MISTACK"); ?></span>
				<span class="page-footer-info"><strong><?php echo $tBigLB;?></strong></span>
			</div>
			<div class="col s3 text-center">
				<span class="page-footer-info"><?php echo $tr->translate("OTHER"); ?></span>
				<span class="page-footer-info"><strong><?php echo $tOtherLB;?></strong></span>
			</div>
		</div>
	</div>
</div>
<!-- Modal Structure -->
<div id="modal-popup" class="modal bottom-sheet modal-popup-info">
	<div class="modal-content content-info">
	</div>
	<div class="modal-footer">
	</div>
</div>
<script type="text/javascript">
	$("select").formSelect(); 
	<?php if(!empty($this->row)){ if(count($this->row) < $this->allRow){?>
		var allRecord ='<?php echo $this->allRow; ?>';
		
		var trackPage = 1;
		var check = 1;
   
		$(window).scroll(function() {
		   if($(window).scrollTop() + $(window).height() > $(document).height() - 1) {
			   if(check==1){
				  loadContents();
				}
		   }
		});

		function loadContents(){
			check=0;
			var urlMoreRow = '<?php echo $this->baseUrl().'/section/attendance/morerecord/'.$querystring; ?>';
			$("#preLoadRecord").addClass("active");
			$.ajax({
				url:urlMoreRow,
				type: "post",
				data: {
					'page':trackPage
					
				},
				dataType: "json",
				success: function(data){
					
					trackPage = data.trackPage;
					if(trackPage>allRecord){
					   trackPage = allRecord;
					   $('.recordMessage').html('');
						
					}else{
						$('.recordMessage').html('<?php echo $tr->translate("SCROLL_FOR_MORE_DATA");?>');
						setTimeout(function () {
							check = 1;
						}, 1000);
					}
					setTimeout(function () {
						$('#totalRecord').html(trackPage+' /'+allRecord);
						$("#listRecord").append(data.htmlRecord);
						$("#preLoadRecord").removeClass("active");
					}, 500);
					
				  
					
				},
				error: function(err) {
					alert(err);
				}
			});

		}
	<?php } ?>
	function getPopupContent(yearMonth,group){
		$('.preloader-background').css("display","flex");
		var urlEvaluationRow = '<?php echo $this->baseUrl().'/section/mistake/detailcontent'; ?>';
			$.ajax({
				url:urlEvaluationRow,
				type: "post",
				data: {
					'id':yearMonth
					,'group':group
					
				},
				dataType: "json",
				success: function(data){
					
					$('.content-info').html(data.htmlRecord);
					setTimeout(function () {
						$('#modal-popup').modal('open');
						$('.preloader-background').delay(10).fadeOut('slow');
					}, 500);
					
				},
				error: function(err) {
					$('.preloader-background').delay(10).fadeOut('slow');
					alert(err);
				}
			});

	}
	<?php } ?>
</script>

