 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("STUDY_RESULT"));
	echo $this->headTitle();
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$currentlang = $dbGb->currentlang();
	$systemLink = $dbGb->systemLink();
	
	$frm = $this->formFilter;
	$querystring = $this->queryString;
?>
<div class="bgBodyhome"></div>	
<div class="bgBody-listview gradientBlue">
	<div class="container">
		<div class="section">
			<div class="row">
				<div class="col s12 pad-0 blog-page-title">
					<div class="page-icon">
						<div class="icon-img">
							<div class="icon-inc-img iconscore"></div>
						</div>
					</div>
					<h5 class="sec-page-tit  ">
						<?php echo $tr->translate("STUDY_RESULT"); ?>
					</h5>
					<span class="sec-page-desc">
						<?php echo $tr->translate("SCORE_PAGE_DESC"); ?>
					</span>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="main-page-list">
	<div  class="bl-score-list-row ">
		<div class="spacer-small"></div>
		<div class="spacer-medium"></div>
		
		<div class="container">
			<div class="row mrg-0">
				<div id="listRecord" class="col s12 pad-0">
					<?php if(!empty($this->row)){ foreach($this->row AS $score){?>
					
					<?php 
						$rank = $score['rank']; 
						$forMonthTitle = $score['forMonthTitle']; 
						$academicYearTitle = $score['academicYearTitle']; 
						$totalScore = $score['totalScore'];
						$totalAvg = $score['totalAvg'];
						$amountStudent = sprintf('%02d',$score['amountStudent']);
						if($currentlang==1){
							$rank = $dbGb->getNumberInkhmer($rank);
							$forMonthTitle = $dbGb->getNumberInkhmer($forMonthTitle);
							$academicYearTitle = $dbGb->getNumberInkhmer($academicYearTitle);
							
							$totalScore = $dbGb->getNumberInkhmer($totalScore);
							$totalAvg = $dbGb->getNumberInkhmer($totalAvg);
							$amountStudent = $dbGb->getNumberInkhmer($amountStudent);
						}
					?>
					<div class="ui-grids scoreList">
						<div class="row ">
							<div class="col s7 blg-score-left">
								<h3 class="title-score"><?php echo $score['forTypeTitle']; ?> <strong class="mark-title"><?php echo $forMonthTitle; ?></strong> </h3>
								<span class="score-info"><strong class="mark-title"><?php echo $academicYearTitle; ?></strong></span>
								<span class="score-info"><?php echo $tr->translate("CLASS_NAME"); ?> <strong class="mark-title"><?php echo $score['groupCode']; ?></strong></span>
								<span class="score-info"><?php echo $tr->translate("TEACHER"); ?> <strong class="mark-title"><?php echo $score['teacherName']; ?></strong></span>
								<span class="score-info"><?php echo $tr->translate("AMT_STUDENT"); ?> <strong class="mark-title"><?php echo $amountStudent." ".$tr->translate("STU_UNIT"); ?></strong></span>
								</div>
							<div class="col s5 blg-score-right">
								<h2 class="ranking"><?php echo $rank; ?></h2>
								<span class="score-info"><?php echo $tr->translate("TOTAL_SCORE"); ?> <strong class="mark-title"><?php echo $totalScore; ?></strong></span>
								<span class="score-info"><?php echo $tr->translate("AVERAGE"); ?> <strong class="mark-title"><?php echo $totalAvg; ?></strong></span>
								<div class="spacer-small"></div>
								<div class="spacer-small"></div>
								<a class="waves-effect waves-light btn btn-rounded  lighten-2" onClick="getPopupContent(<?php echo $score['id'];?>);" >
									<?php echo $tr->translate("MORE_DETAIL"); ?>
								</a>
							</div>
						</div>
					</div>
					<?php } ?>
					
				</div>
			</div>
			<?php if(count($this->row)<$this->allRow){ ?>
			<div class="row mrg-0">
				<div class="col s12 center " >
					<p id="totalRecord" class="total-record"><?php echo count($this->row)."/".$this->allRow; ?></p>
					<h3 class="title-empty recordMessage"><?php echo $tr->translate("SCROLL_FOR_MORE_DATA"); ?></h3>
				</div>
			</div>
			<div class="row mrg-0">
				<div class="col s12 center valign-wrapper" style="height: 100px;">
					<div id="preLoadRecord" class="preloader-wrapper small ">
						<div class="spinner-layer spinner-blue">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>

						<div class="spinner-layer spinner-red">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>

						<div class="spinner-layer spinner-yellow">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>

						<div class="spinner-layer spinner-green">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		<?php } ?>
		</div>
	</div>
	<?php } ?>
	<div class="spacer-xlarge"></div>
</div>

<div id="modal-popup" class="modal bottom-sheet modal-popup-info">
	<div class="modal-content content-info">
		
	</div>
</div>
<!-- Modal Structure -->
<div id="modalFilter" class="modal bottom-sheet white dark-text">
	<div class="modal-content">
		<div class="container">
			<div class="section ui-select">
				<form method="GET">
					<div class="row ">
						<div class="col s12 pad-0"><h5 class="bot-20 sec-tit  "><?php echo $tr->translate("FILTER"); ?></h5>        
							<div class="row">
								<div class="input-field colLeft col s6">
									<?php echo $frm->getElement('academicYear');?>
								  <label><?php echo $tr->translate("ACADEMIC_YEAR"); ?></label>
								</div>
								<div class="input-field colRight col s6">
									<?php echo $frm->getElement('examType');?>
								  <label><?php echo $tr->translate("EXAM_TYPE"); ?></label>
								</div>
								<div class="input-field colLeft col s6">
									<?php echo $frm->getElement('month');?>
								  <label><?php echo $tr->translate("MONTH"); ?></label>
								</div>
								<div class="input-field colRight col s6">
									<?php echo $frm->getElement('forSemester');?>
								  <label><?php echo $tr->translate("SEMESTER"); ?></label>
								</div>
								
								<div class="input-field  col s12">
									<button type="submit" class="fullsize waves-effect waves-light btn btn-rounded primary lighten-2 preloader-trigger" name="search"><?php echo $tr->translate("SEARCH"); ?></button>
								</div>
							</div>
							
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$("select").formSelect();
	$(document).ready(function(){
		checkingExam();
	});
	function checkingExam(){
		var examType = $('#examType').find(":selected").val();
		
		$('#month').prop('disabled', false);
		if(examType==2){
			 $('#month').prop('disabled', 'disabled');
		}
		$("#month").formSelect();
	}		
	<?php if(!empty($this->row)){ if(count($this->row) < $this->allRow){?>
		var allRecord ='<?php echo $this->allRow; ?>';
		
		var trackPage = 1;
		var check = 1;
   
		$(window).scroll(function() {
		   if($(window).scrollTop() + $(window).height() > $(document).height() - 1) {
			   if(check==1){
				  loadContents();
				}
		   }
		});

		function loadContents(){
			check=0;
			var urlMoreRow = '<?php echo $this->baseUrl().'/section/score/morerecord/'.$querystring; ?>';
			$("#preLoadRecord").addClass("active");
			$.ajax({
				url:urlMoreRow,
				type: "post",
				data: {
					'page':trackPage
					
				},
				dataType: "json",
				success: function(data){
					
					trackPage = data.trackPage;
					if(trackPage>allRecord){
					   trackPage = allRecord;
					   $('.recordMessage').html('');
						
					}else{
						$('.recordMessage').html('<?php echo $tr->translate("SCROLL_FOR_MORE_DATA");?>');
						setTimeout(function () {
							check = 1;
						}, 1000);
					}
					setTimeout(function () {
						$('#totalRecord').html(trackPage+' /'+allRecord);
						$("#listRecord").append(data.htmlRecord);
						$("#preLoadRecord").removeClass("active");
					}, 500);
					
				  
					
				},
				error: function(err) {
					alert(err);
				}
			});

		}
	<?php } ?>
	
	function getPopupContent(scoreKey){
		$('.preloader-background').css("display","flex");
		var urlDetailContent = '<?php echo $this->baseUrl().'/section/score/detailcontent'; ?>';
			$.ajax({
				url:urlDetailContent,
				type: "post",
				data: {
					'id':scoreKey
				},
				dataType: "json",
				success: function(data){
					
					$('.content-info').html(data.htmlRecord);
					setTimeout(function () {
						$('#modal-popup').modal('open');
						$('.preloader-background').delay(10).fadeOut('slow');
					}, 50);
					
					
				},
				error: function(err) {
					$('.preloader-background').delay(10).fadeOut('slow');
					alert(err);
				}
			});

	}
	<?php } ?>
</script>

