 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("NEWS"));
	echo $this->headTitle();
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$systemLink = $dbGb->systemLink();
	$currentlang = $dbGb->currentlang();
	
	$row = $this->row;
	$yearAtt = date("Y",strtotime($row['publish_date'])); 
	$monthAtt = date("M",strtotime($row['publish_date'])); 
	$days = date("d",strtotime($row['publish_date'])); 
	$monthKey = date("m",strtotime($row['publish_date'])); 
	
	if($currentlang==1){
		
		$yearAtt = $dbGb->getNumberInkhmer($yearAtt);
		$monthAtt = $dbGb->getMonthInkhmer($monthKey);
		$days = $dbGb->getNumberInkhmer($days);
		
	}
	
?>
<div class="bgBodyhome"></div>	
<div class="bgWhite-for-list "></div>

<div class="container">
    <div class="section">
		<div class="row ui-mediabox blogs bot-0">
			<div class="col s12">
				<?php 
				$images = $this->baseUrl()."/images/no-photo.png";
				$imageFeature = $systemLink.'/images/newsevent/'.$row['image_feature'];
				if ($dbGb->does_url_exists($imageFeature)){
						
				?>
				<a class="img-wrap" href="<?php echo $imageFeature; ?>" data-fancybox="images" data-caption="<?php echo $row['title']; ?>">
					<img class="z-depth-1" style="width: 100%;" src="<?php echo $imageFeature; ?>">
				</a>
				<?php }else{ ?>
				<div class="spacer"></div>
				<div class="spacer"></div>
				<?php }?>
				<h5 class="title"><?php echo $row['title']; ?></h5>
				<span class="small date"><i class="mdi mdi-calendar-clock "></i> <?php echo $days." ".$monthAtt." ".$yearAtt?></span>
				
				<div class="text description"><p class="bot-0 text">
				<?php echo $row['description']; ?>
				</p>

				<div class="spacer"></div>
				<div class="divider"></div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="spacer-xlarge"></div>

 <!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - START --> 
<link href="<?php echo $this->baseUrl()."/templates/"; ?>assets/plugins/fancybox/jquery.fancybox.min.css" rel="stylesheet" type="text/css" media="screen"/>        <!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - END --> 

<!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - START --> 
<script src="<?php echo $this->baseUrl()."/templates/"; ?>assets/plugins/fancybox/jquery.fancybox.min.js" type="text/javascript"></script>
<script type="text/javaScript">
  $("[data-fancybox=images]").fancybox({
  buttons : [ 
    "slideShow",
    "share",
    "zoom",
    "fullScreen",
    "close",
    "thumbs"
  ],
  thumbs : {
    autoStart : false
  }
});
</script><!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - END --> 
