 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("NEWS"));
	echo $this->headTitle();
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$systemLink = $dbGb->systemLink();
	$currentlang = $dbGb->currentlang();
	
	$countNews = count($this->rs);
?>
<div class="bgBodyhome"></div>	
<div class="bgWhite-for-list "></div>
<div class="bgBody-listview gradientBluePrimary">
	<div class="container">
		<div class="section">
			<div class="row">
				<div class="col s12 pad-0 blog-page-title">
					<div class="page-icon">
						<i class="mdi mdi-library-books "></i>
					</div>
					<h5 class="sec-page-tit  ">
						<?php echo $tr->translate("NEWS"); ?>
					</h5>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container">
    <div class="section">
		<div id="listRecord" class="row ui-mediabox blogs    ">
			<?php if(!empty($this->rs)){ foreach($this->rs AS $row){
				 
				$strDescription = mb_substr(strip_tags($row['description']), 0, 150, "UTF-8");
				 
				$yearAtt = date("Y",strtotime($row['publish_date'])); 
				$monthAtt = date("M",strtotime($row['publish_date'])); 
				$days = date("d",strtotime($row['publish_date'])); 
				$monthKey = date("m",strtotime($row['publish_date'])); 
				
				$images = $this->baseUrl()."/images/no-photo.png";
				$imageFeature = $systemLink.'/images/newsevent/'.$row['image_feature'];
				if ($dbGb->does_url_exists($imageFeature)){
					$images = $systemLink.'/images/newsevent/'.$row['image_feature'];
				}
				if($currentlang==1){
					
					$yearAtt = $dbGb->getNumberInkhmer($yearAtt);
					$monthAtt = $dbGb->getMonthInkhmer($monthKey);
					$days = $dbGb->getNumberInkhmer($days);
					
					//$strDescription = mb_substr(strip_tags($row['description']), 0, 200, "UTF-8");
				}
							
				?>	
			<div class="col s12">
				<div class="blog-img-wrap">
					<a class="img-wrap" href="<?php echo $images; ?>" data-fancybox="images" data-caption="<?php echo $row['title']; ?>">
					<img class="z-depth-1" style="width: 100%;" src="<?php echo $images; ?>">
					</a>
				</div>
				<div class="blog-info">
					<a href="<?php echo $this->baseUrl()."/utility/news/detail/id/".$row['id']; ?>" >                    
						<h5 class="title"><?php echo $row['title']; ?></h5>
					</a>
					<span class="small date"><i class="mdi mdi-calendar-clock "></i> <?php echo $days." ".$monthAtt." ".$yearAtt?></span>
					                              
					<p class="bot-0 text"><?php echo $strDescription;   ?>...</p>
					<div class="spacer"></div>
					<div class="divider"></div>
					<div class="spacer"></div>
				</div>
			</div>
			<?php } }?>
		</div>
		
<?php if(count($this->rs)<$this->allRow){ ?>
			<div class="row mrg-0">
				<div class="col s12 center " >
					<p id="totalRecord" class="total-record dark-text"><?php echo $countNews."/".$this->allRow; ?></p>
					<h3 class="title-empty recordMessage dark-text"><?php echo $tr->translate("SCROLL_FOR_MORE_DATA"); ?></h3>
				</div>
			</div>
			<div class="row mrg-0">
				<div class="col s12 center valign-wrapper" style="height: 100px;">
					<div id="preLoadRecord" class="preloader-wrapper small ">
						<div class="spinner-layer spinner-blue">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>

						<div class="spinner-layer spinner-red">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>

						<div class="spinner-layer spinner-yellow">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>

						<div class="spinner-layer spinner-green">
							<div class="circle-clipper left">
								<div class="circle"></div>
							</div>
							<div class="gap-patch">
								<div class="circle"></div>
							</div>
							<div class="circle-clipper right">
								<div class="circle"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		
		<?php } ?>
	</div>
</div>

<div class="spacer-xlarge"></div>

 <!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - START --> 
<link href="<?php echo $this->baseUrl()."/templates/"; ?>assets/plugins/fancybox/jquery.fancybox.min.css" rel="stylesheet" type="text/css" media="screen"/>        <!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - END --> 

<!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - START --> 
<script src="<?php echo $this->baseUrl()."/templates/"; ?>assets/plugins/fancybox/jquery.fancybox.min.js" type="text/javascript"></script>
<script type="text/javaScript">
  $("[data-fancybox=images]").fancybox({
  buttons : [ 
    "slideShow",
    "share",
    "zoom",
    "fullScreen",
    "close",
    "thumbs"
  ],
  thumbs : {
    autoStart : false
  }
});

<?php if(!empty($this->rs)){ if(count($countNews) < $this->allRow){?>
		var allRecord ='<?php echo $this->allRow; ?>';
		
		var trackPage = 1;
		var check = 1;
   
		$(window).scroll(function() {
		   if($(window).scrollTop() + $(window).height() > $(document).height() - 1) {
			   if(check==1){
				  loadContents();
				}
		   }
		});

		function loadContents(){
			check=0;
			var urlMoreRow = '<?php echo $this->baseUrl().'/utility/news/morerecord'; ?>';
			$("#preLoadRecord").addClass("active");
			
			$.ajax({
				url:urlMoreRow,
				type: "post",
				data: {
					'page':trackPage
					
				},
				dataType: "json",
				success: function(data){
					
					trackPage = data.trackPage;
					if(trackPage>allRecord){
					   trackPage = allRecord;
					   $('.recordMessage').html('');
						
					}else{
						$('.recordMessage').html('<?php echo $tr->translate("SCROLL_FOR_MORE_DATA");?>');
						setTimeout(function () {
							check = 1;
						}, 1000);
					}
					setTimeout(function () {
						$('#totalRecord').html(trackPage+' /'+allRecord);
						$("#listRecord").append(data.htmlRecord);
						$("#preLoadRecord").removeClass("active");
					}, 500);
					
				  
					
				},
				error: function(err) {
					alert(err);
				}
			});

		}
	<?php } ?>
	<?php } ?>
</script><!-- OTHER SCRIPTS INCLUDED ON THIS PAGE - END --> 
