 <?php
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("ABOUTS"));
	echo $this->headTitle();
	
	$baseUrl = Application_Form_FrmMessage::getUrl("/");
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$systemLink = $dbGb->systemLink();
	
?>
<div class="bgBodyhome"></div>	
<div class="bgWhite-for-list "></div>
<div class="bgBody-listview gradientBluePrimary">
	<div class="container">
		<div class="section">
			<div class="row">
				<div class="col s12 pad-0 blog-page-title">
					<div class="page-icon">
						<div class="icon-img">
							<div class="icon-inc-img iconabout"></div>
						</div>
					</div>
					<h5 class="sec-page-tit  ">
						<?php echo $tr->translate("ABOUTS"); ?>
					</h5>
				</div>
			</div>
		</div>
	</div>
</div>
<?php if(!empty($this->aboutUs)){ foreach($this->aboutUs AS $aboutUs){?>	
 <div class="container">
	<div class="section">
		<div class="row">
			<div class="spacer"></div>
			<h5 class="center bot-20 sec-tit sectionTitle"><?php echo $aboutUs['title']; ?></h5>
			
			<div class="text description"><?php echo $aboutUs['description']; ?></div>
		</div>
	</div>
</div>
<?php } }?>
<div class="spacer-xlarge"></div>


